app = 'whatsinthebox-db'

[build]
  image = "flyio/postgres-flex:15.3"

[env]
  PRIMARY_REGION = "mad"

[checks]
  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

[[mounts]]
  destination = "/data"
  source = "pg_data"

[metrics]
  path = "/metrics"
  port = 9187